### PR TITLE
Revert hooks to how they looked in vivid

### PR DESCRIPTION
**Pull request by mariogrip**
This fixes https://github.com/ubports/ubuntu-touch/issues/667 and https://github.com/ubports/ubuntu-touch/issues/665 and https://github.com/ubports/ubuntu-touch/issues/582

And might even have positive effect on https://github.com/ubports/ubuntu-touch/issues/611 and https://github.com/ubports/ubuntu-touch/issues/514

This will need testing on a handful of different devices, since it's a critical part.

### CODE REVIEW

**Review by NeoTheThird — APPROVED** [review]
Looks syntactically correct, but i can't comment on how it will behave in the field. Are we feeling lucky enough to just merge it and clean up after the desaster later?

**Comment by mariogrip** [comment]
Sure, it works on all devices i have tested. (n5, m10, pro5 and mx4) and since it's the same as vivid i will be surprised if fails

**Comment by hoh61** [comment]
How can I test it?

**Comment by NeoTheThird** [comment]
Just install the latest devel update, it's already out. The alternative would have been to [install the artifacts](https://ci.ubports.com/blue/organizations/jenkins/ubports%2Flibhybris/detail/xenial_-_camera-test/4/artifacts)

**Pull request merged**
