### PR TITLE
 hooks: hack for PowerVR crashes on MX4

### PR DESCRIPTION
**Pull request by fredldotme**
The MX4 has issues starting unity-system-compositor due to
some blob creating format strings with floats and failing.
This change adds an ugly hack to work around those issues,
specifically blacklisting of the offending vsnprintf calls.

The hack has to be removed sometime, but push it now to unblock
edge from shipping more changes related to this issue.

Fixes https://github.com/ubports/ubuntu-touch/issues/1052

### CODE REVIEW

**Comment by fredldotme** [comment]
I can extend the hack so it only blacklists on arale/MX4.

EDIT: done

**Comment by NeoTheThird** [comment]
This is for https://github.com/ubports/ubuntu-touch/issues/1052, right?

**Review by mariogrip — APPROVED** [review]
LGTM :+1: Nice work! :)

**Comment by fredldotme** [comment]
> This is for [ubports/ubuntu-touch#1052](https://github.com/ubports/ubuntu-touch/issues/1052), right?

Yes

> LGTM +1 Nice work! :)

Thanks

The only other issue that needs to be resolved is: https://github.com/ubports/ubuntu-touch-session/issues/6

**Comment by fredldotme** [comment]
What I wanted to add is: yes, the hack has to disappear at one point, but the underlying problem is hard to identify. gdb shows that the first offending vsnprintf tries to insert an integer value from the vsnprintf call before it. This indicates severe memory corruption which has to be dealt with sooner rather than later and might possibly be out of scope for libhybris itself.

**Pull request merged**
